# Site settings
author: Whitney Hodgkins
title: Why Isn't This Working
header-img: img/home-bg.png
email: hodgkins.whitney@gmail.com
copyright_name: Whitney Hodgkins
description: > # this means to ignore newlines until "baseurl:"
  A Creative Pursuit
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rogue-hippie

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
